from typing import Protocol

import pymupdf
from pymupdf.table import TableFinder


class AnnotatedPage(Protocol):
    @property
    def rect(self) -> tuple[float, float]: ...

    @property
    def mediabox(self) -> pymupdf.Rect: ...

    @property
    def rotation(self) -> int: ...

    def find_tables(self, *args, **kwargs) -> TableFinder: ...

    def get_pixmap(self, *args, **kwargs) -> pymupdf.Pixmap: ...

    def get_text(self, option: str, *, sort: bool = True, **kwargs) -> str | list | dict: ...

    def add_rect_annot(self, rect: pymupdf.rect_like) -> pymupdf.Annot: ...

    def add_text_annot(self, *args, **kwargs) -> pymupdf.Annot: ...

    def add_highlight_annot(self, *args, **kwargs) -> pymupdf.Annot: ...

    def insert_font(self, *args, **kwargs) -> pymupdf.CheckFont: ...
